# Generated by Django 4.2 on 2023-04-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_readed_num_readnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
